# Generated by Django 3.0.7 on 2020-07-05 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamecategory',
            old_name='category',
            new_name='name',
        ),
    ]
